### ISSUE TITLE
Invalid source address

### ISSUE THREAD

**Issue by irl** [libparistraceroute/libparistraceroute#17]
```
sudo paris-traceroute 139.133.204.173
terminate called after throwing an instance of 'TrException'
Exception : [ERROR](IP4Header.cc, 239)Invalid source address : 
                                                               V[1]    5758 abort      sudo paris-traceroute 139.133.204.173
```

There does not seem to be an option for setting the source address/interface. This may be related to the fact that my active interface has index 2, with index 1 being a wired interface that is not connected.

**Comment by ibgp2** [comment]
Hi irl,

Sorry for this late answer. You're talking about the legacy version of paris-traceroute (the one written in C++), so this issue should be reported in:
https://github.com/libparistraceroute/paris-traceroute-OLD/issues

Option -s corresponds to the source port (contrary to the new version) and seems to work fine. I cannot reproduce your bug because my network connection is a currently filtered.

```
(mando@aldur) (~/git/github/paris-traceroute-OLD/src) $ sudo ./paris-traceroute -s 11111 192.168.0.254
[sudo] Mot de passe de mando : 
traceroute [(192.168.0.85:11111) -> (192.168.0.254:33457)], protocol udp, algo hopbyhop, duration 0 s
 1  192.168.0.254 (192.168.0.254)  1.760 ms   8.533 ms   1.174 ms
```

Best regards
