### ISSUE TITLE
update_timer passed negative delays

### ISSUE THREAD

**Issue by drt24** [libparistraceroute/libparistraceroute#2]
When running paris-traceroute I get error messages like:

```
update_timer: invalid delay (delay = -0.014287)
Error while updating timeout
```

In network.c update_timer expects a positive value for delay. It is called by `network_update_next_timeout` which calculates the delay to pass to update_timer using `network_get_probe_timeout`. `network_get_probe_timeout`'s documentation says "\return The timeout of the probe. This value may be negative. If so, it means that this probe has already expired and a PROBE_TIMEOUT should be raised."

I am not sure what the fix for this is (hence no patch) should `network_update_next_timeout` have a line like `pt_throw(NULL, probe->caller, event_create(PROBE_TIMEOUT, probe, NULL, NULL));` in `network_drop_expired_flying_probe` which is the other user of `network_get_probe_timeout` or should something be happening in `network_get_matching_probe` (which calls `network_update_next_timeout`) to ensure this can't happen?

**Comment by ibgp2** [comment]
Hi Daniel,

This part of the library has not been so much evaluated so it can be improved. "Flying probe" designs a probe send let say by paris-traceroute, such that the corresponding reply has not been handled.

If my remember is correct the idea of network_update_next_timeout is to update the date where the next probe will expire (among the whole set of probes). So if each probes has the same lifetime it should correspond to the oldest flying probe. It should be a positive value : otherwise it means that the oldest and the 2nd oldest probe have basically "simultaneously" expired. Both of them should trigger a "*" in terms of paris-traceroute output.

So if when updating the next timeout, several probes have already expired (negative timeout), each of them should be dropped and notified to the running algorithm with the appropriate `pt_throw` call. I guess that such a situation  may occur on a slow machine.

`network_get_matching_probe` aims at determining the probe matching a given handled reply, and hence "forward" this reply to the appropriate algorithm instance, so it corresponds to probe where there is (so far) not impacted by a timeout.

To fix the issue properly, I guess that one have to determine the next flying probe not in timeout (if any), and notify each expired probe. In practice, this is already  addressed by `network_drop_expired_flying_probe`.

Correct me if I'm wrong, but I've the feeling that in your case, when `network_drop_expired_flying_probe` is called, you remove some expired probe, but the next flying probe is very close to expire, and has indeed expired when you call `network_update_next_timeout`. If so, the idea would be to increase EXTRA_DELAY value.

Cheers,
M.O.

**Comment by drt24** [comment]
OK. So I think that the fix would be to in `network_get_matching_probe` rather than call `network_update_next_timeout` to directly update the timeout, instead call `network_drop_expired_flying_probe` as that will remove expired probes and then call network_update_next_timeout with the first non-expired probe.
I think that what is triggering the bug is a packet arriving for a probe that has expired but not yet been removed when the probe after it has also expired as the log output indicates that the failure is caused by `network_get_matching_probe` calling `network_update_next_timeout`.

If that sounds sensible I can try and implement that tomorrow.

**Comment by ibgp2** [comment]
I guess that your point should occur if the `network_get_matching_probe` is "enough slow" to make the next probe obsolete before it ends. 

Indeed, if I remember correctly, `network_pudate_next_timeout` will register an event for the next expiring probe. When it occurs, it will raise the appropriate `PROBE_TIMEOUT` notification(s) with `network_drop_expired_flying_probe` (and thus clearing/notifying each obsolete probe).
