### ISSUE TITLE
Reverse TTL Value

### ISSUE THREAD

**Issue by Buslu07** [libparistraceroute/libparistraceroute#29]
I can't find the Reverse TTL functionality from the old paristraceroute Program. I hope you can implement it like in the original traceroute, by showing the difference between send TTL value and reply TTL value.

**Comment by ibgp2** [comment]
Hello Burak5,

This can easily be implemented, but I do not see this option in legacy paris-traceroute:
http://manpages.ubuntu.com/manpages/trusty/man8/paris-traceroute.8.html

Could you provide:
- the command-line that you used with the previous tool, hence we could use the same syntax?
- an example of output when this option is enabled?

Also, could you precise if this option is related to mda (e.g. discovery of the whole set of paths between the source and the target address), to paris-traceroute (e.g. discovery of the path from a source to a destination according to a flow id) or both.

Basically the new paris-traceroute is designed as follows:
- the measurement tools sends some probes
- `libparistraceroute` keeps track of probe id for each flying probe (see `libparistraceroute/network.h`)
- when a reply matching a probe is handled, the appropriate algorithms (see `mda_handler_reply` in `libparistraceroute/algorithm/mda.c`) are notified (the `probe_t` and the `reply_t` instance are parameters of the handler)
- then the application handler is notified, in your case, in `loop_handler` in `paris-traceroute/paris-traceroute.c`)

Since the option is just display, the modification should be implemented in `loop_handler`.
- `traceroute_options` allows to determine whether the reverse_ttl option is enabled
- depending on this, the `mda_link_dump` (see `libparistraceroute/algorithms/mda.c`) and/or `traceroute_handler` function (in charge of displaying the newly discovered links) (see `libparistraceroute/algorithms/traceroute.c`). Everything is ready in `traceroute_handler` to support this new functionnality, because you get the `traceroute_options`, the probe and the reply.

The TTL can be extracted from a probe_t (resp. reply_t) by using:

```
uint8_t ttl_reply;
if (probe_extract(reply, "ttl", &ttl_reply)) {
  printf("%2d", ttl_reply);
}
```

Best regards

**Comment by Buslu07** [comment]
Hi ibgp2,

the first link you posted presents the option to show the TTL Value of the reply with the following option:
"-l Display the ttl value of the reply. Useful to study asymmetric routing and NAT
              boxes."
I need this option to get information about asymmetric routing for more accurate latency calculation.
The last version, which had implemented this functionality was: tupleroute ver. 0.90-dev
and maybe ver. 0.92.
Example:
sudo paris-traceroute --print_ttl google.de
Output:
 6  100.65.8.97 (100.65.8.97)  0.465 ms [250]   1.028 ms [250]   0.512 ms [250]
 7  52.95.3.131 (52.95.3.131)  1.361 ms [249]   1.505 ms [249]   1.315 ms [249]
 8  52.95.1.82 (52.95.1.82)  2.046 ms [243]   9.054 ms [243]   1.728 ms [243]
   MPLS Label 300634 TTL=1
 9  52.95.1.89 (52.95.1.89)  1.290 ms [245]   1.278 ms [245]   1.283 ms [245]

I used the paris-traceroute algorithm.
It would be really nice if you could implement this function and if you want you could go further and implement it like in the original traceroute program, which has the functionality to show the difference between send TTL and reply TTL by assuming that the back TTL value should be a standard value of 64,128 or 255.

This is the part of the original traceroute program which implemented this feature:
```
	if (fp->recv_ttl) {
	    /*  Consider the ttl value of the report packet and guess where
		the "final" should be. If it seems that it should be
		in the same hop as "this", then do replace.
	    */
	    int back_hops, ttl;

	    /*  We assume that the reporting one has an initial ttl value
		of either 64, or 128, or 255. It is most widely used
		in the modern routers and computers.
		The idea comes from tracepath(1) routine.
	    */
	    back_hops = ttl2hops (fp->recv_ttl);

	    /*  It is possible that the back path differs from the forward
		and therefore has different number of hops. To minimize
		such an influence, get the nearest previous time-exceeded
		probe and compare with it.
	    */
	    for (p = pb - 1; p >= probes; p--) {
		if (p->done && !p->final && p->recv_ttl) {
		    int hops = ttl2hops (p->recv_ttl);

		    if (hops < back_hops) {
			ttl = (p - probes) / probes_per_hop + 1;
			back_hops = (back_hops - hops) + ttl;
			break;
		    }
		}
	    }

	    ttl = idx / probes_per_hop + 1;
	    if (back_hops == ttl)
		/*  Yes! It seems that "final" should be at "this" place   */
		goto  replace_by_final;
	    else if (back_hops < ttl)
		/*  Hmmm... Assume better to replace here too...  */
		goto  replace_by_final;

	}

```
with regards
Burak

**Comment by ibgp2** [comment]
Hi burak5,

I did not find this option in https://github.com/libparistraceroute/paris-traceroute-OLD
Could you give the short name of this option (if any) ?

Also could you give me the code of `ttl2hops` ?

Best regards

**Comment by ibgp2** [comment]
1) I'm not sure of the motivation of the piece of code you reported (where is used the assumption related to the initial TTL), how are we supposed to use the probe's TTL, the reply's TTL, and the initial TTL values. Your explanations are welcome.

2) For the moment I assumed that you just want to print the TTL carried by the reply packet. Here is an example of output. Please let me know if this was you wanted. 

```
sudo ./paris-traceroute/paris-traceroute --print-ttl 8.8.8.8
traceroute to 8.8.8.8 (8.8.8.8), 30 hops max, 30 bytes packets
 1  belenos.enst.fr (137.194.164.254)  1.079ms  [64]   1.076ms  [64]   1.080ms  [64] 
 2  asrix.enst.fr (137.194.4.240)  0.900ms  [254]   0.899ms  [254]   0.901ms  [254] 
 3  interco-G06-odeon.rap.prd.fr (195.221.127.185)  1.060ms  [252]   1.065ms  [252]   1.071ms  [252] 
 4  vl260-te4-4-paris1-rtr-021.noc.renater.fr (193.51.186.102)  43.160ms  [246]   43.150ms  [246]   43.166ms  [246] 
 5  xe0-1-0-paris1-rtr-131.noc.renater.fr (193.51.180.32)  2.514ms  [246]   2.503ms  [246]   2.508ms  [246] 
 6  xe1-0-2-paris2-rtr-131.noc.renater.fr (193.51.177.129)  2.242ms  [250]   2.229ms  [250]   2.236ms  [250] 
 7  * * *
 8  72.14.214.160 (72.14.214.160)  2.354ms  [248]   2.348ms  [248]   2.373ms  [248] 
 9  108.170.244.225 (108.170.244.225)  3.476ms  [246]   3.464ms  [246]   3.468ms  [246] 
10  209.85.251.157 (209.85.251.157)  2.055ms  [57]   2.033ms  [57]   2.037ms  [57] 
11  google-public-dns-a.google.com (8.8.8.8)  1.985ms  [122]   1.976ms  [122]   1.987ms  [122]
```
3) If this options is only implemented for `paris-traceroute` but not for MDA, are you ok with this?

Best regards

**Comment by Buslu07** [comment]
1. It was only suggestion ^^.  It is used to check if the Route which a network packet traveled is symmetric, which means it took the same amount of Hops to the destination and the same amount back from Destination to Source (yourself). For Example, if it took 7 Hops to Destination and you send it with a TTL of 64, it arrives with a TTL Value of 57 (correct me if I'm wrong). Now if the Back TTL Value is 50, then you can assume, that the Destination Server sent the Network Packet with an initial TTL Value of 64 (Standard) and that the reverse Path took 14 Hops, which means, that the Route, which the Network Packet traveled is asymmetric. This is important for the calculation of the latency between Source and Destination. For Example, If traceroute reports an RTT of 10ms to the first Hop, but the Reverse TTL Value is weird like in the example before, you can assume, that latency of 5ms would be false because the network packet traveled asymmetric. The calculation of latency is essential if you want to calculate the location of an IP-Adress by using triangulation (my actual Project). It is not seriously necessary to implement this feature, which is performed in the standard traceroute because I could calculate it in my python code, but It would be nice to have 👍 

2. It is ok. Same like in the old Paris-Traceroute.

3. It is ok ^^.

**Comment by ibgp2** [comment]
Pushed, see cf327633863aa51505b02f31ca7ac8f6738e8dc8
